services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting-agent-app
    volumes:
      - .:/code
    depends_on:
      - nats
      - redis
      - qdrant
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NATS_URL=nats://nats:4222
    env_file:
      - .env   # 👈 вот эта строка важна

  nats:
    image: nats:2.9-alpine
    container_name: meeting-agent-nats
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:7-alpine
    container_name: meeting-agent-redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: meeting-agent-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
